### ISSUE TITLE
Production use

### ISSUE THREAD

**Issue by karneaud** [nikersify/fig#1]
Hey!

Stumbled upon your framework as I am a big fan of PugJS and was in search of a framework that uses it. Was quite surprised that I found this. How production ready is this?

**Comment by nikersify** [comment]
Hello!

While I've tried to develop fig to be as stable as possible, I wouldn't necessarily use it for anything serious at this stage of its development.

So far I've only built two small and one medium project with the framework, there definitely wasn't enough time spent with it to find all of its bugs, workarounds for weird problems, update the documentation, etc.

I can only recommend using it to mess around at the moment, possibly report some issues and wait till it gets a bit more stable.

Thank you!

**Comment by karneaud** [comment]
well I think my project is not of great importance and would be a nice "test subject"

**Comment by karneaud** [comment]
I guess web pack integration would be out of the question
