### ISSUE TITLE
Integration into Webpack

### ISSUE THREAD

**Issue by karneaud** [nikersify/fig#2]
How save is it using web pack?

**Comment by nikersify** [comment]
To use fig.js seamlessly you need to transpile `.fig` or `.pug` component files into a format digestable by fig on the front side of things. At the time of writing I've only released [figify](https://github.com/nikersify/figify) for browserify. I don't have much experience with webpack, but I think that you could use [transform-loader](https://github.com/webpack-contrib/transform-loader) to run the browserify transform inside webpack?

**Comment by karneaud** [comment]
using the transform-loader worked!
