### ISSUE TITLE
Plain Pug

### ISSUE THREAD

**Issue by karneaud** [nikersify/fig#3]
Can plain static .pugs be used/ integrated into this? Like mixins and includes and stuff?

**Comment by nikersify** [comment]
As far as my testing went only `extends` is broken, looks like an easy thing to fix though. You can add mixins and includes into your components and they should work just fine.

**Comment by karneaud** [comment]
nice to note it took a bit of getting used to with. I think there might be a problem with the includes in "slots" but still testing
